import type { OpsExecutionSnapshot, OpsTask } from "@/lib/ops/types";

const scenarios = [
  { scenario_id: "hotel_kitchen_fire", label: "Hotel kitchen fire" },
  { scenario_id: "basement_leak", label: "Basement gas leak" },
  { scenario_id: "crowd_panic", label: "Crowd panic" },
  { scenario_id: "icu_oxygen_issue", label: "ICU oxygen issue" },
  { scenario_id: "dual_incident_chain", label: "Dual incident chain" },
];

export function buildLocalOpsExecutionSnapshot(): OpsExecutionSnapshot {
  const generated_at = new Date().toISOString();
  const tasks: OpsTask[] = [
    {
      task_id: "TASK-HOTEL-KITCHEN-FIRE-01",
      title: "Verify source",
      role: "Security",
      owner: "Security Bravo",
      eta: "2 min",
      sla_minutes: 4,
      elapsed_minutes: 2,
      sla_status: "healthy",
      status: "completed",
      dependencies: [],
      confidence: 95,
      notes: "Auto-assigned by role, location, workload, and critical urgency.",
    },
    {
      task_id: "TASK-HOTEL-KITCHEN-FIRE-02",
      title: "Dispatch responders",
      role: "Security",
      owner: "Ops Alpha",
      eta: "1 min",
      sla_minutes: 3,
      elapsed_minutes: 4,
      sla_status: "breached",
      status: "running",
      dependencies: ["verify source"],
      confidence: 93,
      notes: "Backup team ready if responder ETA slips.",
    },
    {
      task_id: "TASK-HOTEL-KITCHEN-FIRE-03",
      title: "Unlock exits",
      role: "Facilities",
      owner: "Facilities Lead",
      eta: "3 min",
      sla_minutes: 5,
      elapsed_minutes: 4,
      sla_status: "watch",
      status: "running",
      dependencies: [],
      confidence: 91,
      notes: "East stairwell prioritized for evacuation flow.",
    },
    {
      task_id: "TASK-HOTEL-KITCHEN-FIRE-04",
      title: "Start evacuation",
      role: "Comms",
      owner: "Comms Desk",
      eta: "4 min",
      sla_minutes: 6,
      elapsed_minutes: 5,
      sla_status: "watch",
      status: "awaiting_approval",
      dependencies: ["unlock exits"],
      confidence: 88,
      notes: "Human approval required for public floor announcement.",
    },
    {
      task_id: "TASK-HOTEL-KITCHEN-FIRE-05",
      title: "Containment verify",
      role: "External",
      owner: "Fire Unit 4",
      eta: "12 min",
      sla_minutes: 15,
      elapsed_minutes: 12,
      sla_status: "healthy",
      status: "blocked",
      dependencies: ["dispatch responders"],
      confidence: 79,
      notes: "Waiting on corridor visibility confirmation.",
    },
  ];
  return {
    generated_at,
    mode: "demo",
    scenarios,
    active_incidents: [
      {
        incident_id: "INC-OPS-001",
        title: "Hotel kitchen fire",
        building: "Grand Meridian Hotel",
        zone: "Kitchen Zone B",
        severity: "critical",
        workflow: "fire",
        recovery_eta: "22 min",
        status: "active",
        confidence: 91,
      },
    ],
    workflow_queue: [
      {
        workflow_id: "WF-HOTEL-KITCHEN-FIRE",
        name: "Fire",
        incident_id: "INC-OPS-001",
        scenario: "hotel_kitchen_fire",
        status: "active",
        progress: 14,
        tasks_total: 7,
        tasks_completed: 1,
        owner: "Ops Alpha",
        started_at: generated_at,
      },
    ],
    tasks,
    task_board: {
      queued: tasks.filter((task) => task.status === "queued"),
      running: tasks.filter((task) => task.status === "running"),
      blocked: tasks.filter((task) => task.status === "blocked"),
      awaiting_approval: tasks.filter((task) => task.status === "awaiting_approval"),
      completed: tasks.filter((task) => task.status === "completed"),
    },
    sla_timers: tasks.map((task) => ({
      task_id: task.task_id,
      title: task.title,
      owner: task.owner,
      remaining_minutes: Math.max(0, task.sla_minutes - task.elapsed_minutes),
      sla_status: task.sla_status,
      escalation_level: task.sla_status === "breached" ? 1 : 0,
    })),
    teams: [
      { department: "Security", capacity: 14, load: 9, readiness: 91, lead: "Security Bravo", status: "active" },
      { department: "Medical", capacity: 8, load: 5, readiness: 88, lead: "Medical Unit 2", status: "active" },
      { department: "Facilities", capacity: 10, load: 7, readiness: 86, lead: "Facilities Lead", status: "active" },
      { department: "Comms", capacity: 6, load: 3, readiness: 93, lead: "Comms Desk", status: "ready" },
      { department: "Executive", capacity: 4, load: 2, readiness: 89, lead: "Executive Liaison", status: "ready" },
    ],
    blockers: [
      {
        blocker_id: "BLK-TASK-HOTEL-KITCHEN-FIRE-05",
        task_id: "TASK-HOTEL-KITCHEN-FIRE-05",
        title: "Containment verify blocked",
        risk: "SLA breach may delay incident resolution",
        owner: "Fire Unit 4",
        recommended_action: "Reassign backup team and notify leadership",
      },
    ],
    escalation_queue: tasks
      .filter((task) => task.sla_status !== "healthy")
      .map((task) => ({
        escalation_id: `ESC-${task.task_id}`,
        level: task.sla_status === "breached" ? 1 : 0,
        task_id: task.task_id,
        title: task.title,
        action: task.sla_status === "breached" ? "Notify leadership and trigger backup team" : "Monitor",
        owner: task.owner,
      })),
    approval_center: [
      {
        approval_id: "APR-TASK-HOTEL-KITCHEN-FIRE-04",
        task_id: "TASK-HOTEL-KITCHEN-FIRE-04",
        title: "Start evacuation",
        owner: "Comms Desk",
        risk_score: 72,
        recommendation: "Approve to continue governed workflow",
      },
    ],
    completion: {
      progress: 20,
      tasks_completed: 1,
      tasks_total: 5,
      resolution_confidence: 88,
    },
    governance: {
      mode: "approval_required",
      available_modes: ["advisory", "approval_required", "semi_auto", "full_auto"],
      actions: ["approve_workflow", "pause_workflow", "reject_task", "manual_override", "reassign_owner"],
    },
    resolution_ledger: [
      {
        timestamp: generated_at,
        event: "Execution engine online",
        detail: "Autonomous operations engine initialized in local fallback mode.",
        status: "verified",
      },
    ],
    executive_summary: {
      incidents_active: 1,
      avg_response_time: "6m 40s",
      tasks_completed: 1,
      sla_success: "80%",
      estimated_losses_avoided: "$480K",
      recovery_eta: "22 min",
      running_tasks: 2,
    },
  };
}
