from __future__ import annotations

from app.marketplace.models import app


MARKETPLACE_APPS: tuple[dict[str, object], ...] = (
    app(app_id="APP-SLACK-CRISIS", name="Slack Crisis Bridge", slug="slack-crisis-bridge", vendor="Salesforce", category="communication", description="Premium Slack incident rooms, command approvals, and responder escalation workflows.", logo_key="slack-crisis", pricing_model="per_workspace", rating=4.9, review_count=1540, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="low", tags=["chat", "crisis bridge", "incident rooms"], version="4.2.0", monthly_price=129, trial_available=True, featured=True),
    app(app_id="APP-TEAMS-COMMAND", name="Microsoft Teams Command Alerts", slug="teams-command-alerts", vendor="Microsoft", category="communication", description="Teams command alerts with executive approval cards and live status sync.", logo_key="teams-command", pricing_model="included", rating=4.8, review_count=1320, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="low", tags=["teams", "alerts", "approvals"], version="3.1.0", monthly_price=99, trial_available=True, featured=True),
    app(app_id="APP-WHATSAPP-PRO", name="WhatsApp Broadcast Pro", slug="whatsapp-broadcast-pro", vendor="Meta", category="communication", description="Approved WhatsApp emergency templates, retry paths, and tenant-safe broadcast analytics.", logo_key="whatsapp-pro", pricing_model="usage_based", rating=4.7, review_count=920, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="medium", tags=["whatsapp", "broadcast", "mass notification"], version="2.4.1", monthly_price=159, trial_available=True, featured=True),
    app(app_id="APP-SAP-INCIDENT", name="SAP Incident Sync", slug="sap-incident-sync", vendor="SAP", category="business_systems", description="Sync Sentra incidents into SAP continuity, procurement, and facility operations workflows.", logo_key="sap-incident", pricing_model="enterprise", rating=4.7, review_count=760, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="high", tags=["sap", "erp", "incident sync"], version="3.8.0", monthly_price=649, trial_available=False, featured=True),
    app(app_id="APP-SALESFORCE-RISK", name="Salesforce Risk Connector", slug="salesforce-risk-connector", vendor="Salesforce", category="business_systems", description="Connect account risk, renewals, and enterprise incident intelligence into Salesforce.", logo_key="salesforce-risk", pricing_model="enterprise", rating=4.8, review_count=1110, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="high", tags=["salesforce", "risk", "crm"], version="5.5.0", monthly_price=429, trial_available=True, featured=True),
    app(app_id="APP-SNOW-RESPONSE", name="ServiceNow Response Flow", slug="servicenow-response-flow", vendor="ServiceNow", category="itsm_ticketing", description="Automated response tickets, SLA escalations, and post-incident recovery tasks.", logo_key="snow-response", pricing_model="enterprise", rating=4.8, review_count=1180, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="high", tags=["servicenow", "workflow", "response"], version="4.8.2", monthly_price=399, trial_available=True, featured=True),
    app(app_id="APP-GMAPS-EVAC", name="Google Maps Evac Layer", slug="google-maps-evac-layer", vendor="Google", category="maps_location", description="Evacuation routing overlays, blocked corridor avoidance, and executive safe extraction paths.", logo_key="gmaps-evac", pricing_model="usage_based", rating=4.9, review_count=1460, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="medium", tags=["maps", "evacuation", "routes"], version="5.4.0", monthly_price=249, trial_available=True, featured=True),
    app(app_id="APP-DRONE-FLEET", name="Drone Fleet Control", slug="drone-fleet-control", vendor="SkyOps Robotics", category="field_facility_iot", description="Dispatch inspection drones, perimeter sweeps, and aerial verification in approved public zones.", logo_key="drone-fleet", pricing_model="per_device", rating=4.6, review_count=380, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="high", tags=["drones", "field", "verification"], version="1.9.0", monthly_price=699, trial_available=False, featured=True),
    app(app_id="APP-VISITOR-SHIELD", name="Visitor Access Shield", slug="visitor-access-shield", vendor="SecureEntry Labs", category="security", description="Visitor access risk, badge revocation, and evacuation-safe occupancy signals.", logo_key="visitor-shield", pricing_model="per_site", rating=4.7, review_count=640, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="medium", tags=["access", "visitor", "security"], version="2.6.3", monthly_price=299, trial_available=True, featured=False),
    app(app_id="APP-POWER-GRID", name="Power Grid Watch", slug="power-grid-watch", vendor="GridPulse", category="field_facility_iot", description="Power failure chain reaction alerts, generator telemetry, and facility resilience triggers.", logo_key="power-grid", pricing_model="enterprise", rating=4.6, review_count=420, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="high", tags=["power", "utilities", "resilience"], version="2.2.0", monthly_price=379, trial_available=True, featured=False),
    app(app_id="APP-BOARD-PDF", name="Board PDF Exporter", slug="board-pdf-exporter", vendor="Sentra", category="business_systems", description="Board-ready PDF exports for incident summaries, trust evidence, and executive reviews.", logo_key="board-pdf", pricing_model="included", rating=4.9, review_count=820, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="low", tags=["pdf", "board", "reports"], version="1.5.0", monthly_price=79, trial_available=True, featured=False),
    app(app_id="APP-AI-VOICE", name="AI Voice Call Escalation", slug="ai-voice-call-escalation", vendor="VoiceOps AI", category="communication", description="Audited voice call escalation with synthetic scripts, retry queues, and executive fallback.", logo_key="ai-voice", pricing_model="usage_based", rating=4.7, review_count=520, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="medium", tags=["voice", "ai", "escalation"], version="2.0.1", monthly_price=219, trial_available=True, featured=True),
    app(app_id="APP-SLACK", name="Slack", slug="slack", vendor="Salesforce", category="communication", description="Route critical Sentra alerts to Slack channels and incident rooms.", logo_key="slack", pricing_model="per_workspace", rating=4.8, review_count=1240, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="low", tags=["chat", "alerts", "incident rooms"], version="3.4.2", monthly_price=79, trial_available=True, featured=True),
    app(app_id="APP-TEAMS", name="Microsoft Teams", slug="microsoft-teams", vendor="Microsoft", category="communication", description="Push command updates into Teams channels with executive escalation cards.", logo_key="teams", pricing_model="included", rating=4.7, review_count=1160, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="low", tags=["chat", "enterprise", "approvals"], version="2.9.0", monthly_price=69, trial_available=True, featured=True),
    app(app_id="APP-TWILIO", name="Twilio", slug="twilio", vendor="Twilio", category="communication", description="SMS, voice, and WhatsApp notification paths for field and occupant alerts.", logo_key="twilio", pricing_model="usage_based", rating=4.8, review_count=980, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="medium", tags=["sms", "voice", "emergency alerts"], version="4.1.1", monthly_price=149, trial_available=True, featured=True),
    app(app_id="APP-WHATSAPP", name="WhatsApp Business", slug="whatsapp-business", vendor="Meta", category="communication", description="Approved WhatsApp templates for occupant and stakeholder crisis communication.", logo_key="whatsapp", pricing_model="usage_based", rating=4.6, review_count=740, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="medium", tags=["messaging", "public alerts"], version="1.8.4", monthly_price=119, trial_available=True, featured=False),
    app(app_id="APP-ZOOM", name="Zoom", slug="zoom", vendor="Zoom", category="communication", description="Launch emergency coordination bridges directly from Sentra incident plans.", logo_key="zoom", pricing_model="per_workspace", rating=4.6, review_count=860, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="low", tags=["video", "war room"], version="2.5.3", monthly_price=59, trial_available=True, featured=False),
    app(app_id="APP-GMEET", name="Google Meet", slug="google-meet", vendor="Google", category="communication", description="Create secure Meet rooms for executive and responder coordination.", logo_key="google-meet", pricing_model="included", rating=4.5, review_count=610, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="low", tags=["video", "workspace"], version="1.7.0", monthly_price=49, trial_available=True, featured=False),
    app(app_id="APP-SMTP", name="SMTP Email Relay", slug="smtp-email-relay", vendor="Sentra", category="communication", description="Bring your authorized SMTP relay for audited email notifications.", logo_key="smtp", pricing_model="free", rating=4.4, review_count=320, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="medium", tags=["email", "compliance"], version="1.2.0", monthly_price=0, trial_available=False, featured=False),
    app(app_id="APP-GMAPS", name="Google Maps", slug="google-maps", vendor="Google", category="maps_location", description="Premium geocoding, route intelligence, and live map overlays.", logo_key="google-maps", pricing_model="usage_based", rating=4.8, review_count=1340, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="medium", tags=["maps", "routing", "geocoding"], version="5.0.0", monthly_price=199, trial_available=True, featured=True),
    app(app_id="APP-MAPBOX", name="Mapbox", slug="mapbox", vendor="Mapbox", category="maps_location", description="High-performance location rendering and custom crisis map styling.", logo_key="mapbox", pricing_model="usage_based", rating=4.7, review_count=920, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="medium", tags=["maps", "digital twin"], version="3.2.1", monthly_price=179, trial_available=True, featured=True),
    app(app_id="APP-HERE", name="HERE Maps", slug="here-maps", vendor="HERE", category="maps_location", description="Enterprise-grade routing, traffic, and public safety corridor support.", logo_key="here", pricing_model="usage_based", rating=4.5, review_count=540, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="medium", tags=["traffic", "routes"], version="2.4.6", monthly_price=159, trial_available=True, featured=False),
    app(app_id="APP-OSM-ENT", name="OpenStreetMap Enterprise", slug="openstreetmap-enterprise", vendor="OpenStreetMap Ecosystem", category="maps_location", description="Self-hostable open mapping tiles for private or sovereign deployments.", logo_key="osm", pricing_model="enterprise", rating=4.6, review_count=410, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="high", tags=["open data", "private cloud"], version="1.9.2", monthly_price=99, trial_available=True, featured=False),
    app(app_id="APP-AWS", name="AWS", slug="aws", vendor="Amazon Web Services", category="cloud_infra", description="Route telemetry, archives, and resilient workloads into AWS environments.", logo_key="aws", pricing_model="enterprise", rating=4.8, review_count=1500, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="high", tags=["cloud", "storage", "scale"], version="6.1.0", monthly_price=399, trial_available=False, featured=True),
    app(app_id="APP-AZURE", name="Microsoft Azure", slug="azure", vendor="Microsoft", category="cloud_infra", description="Enterprise deployment, identity, storage, and monitoring integration for Azure.", logo_key="azure", pricing_model="enterprise", rating=4.8, review_count=1390, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="high", tags=["cloud", "identity", "government"], version="5.8.1", monthly_price=399, trial_available=False, featured=True),
    app(app_id="APP-GCP", name="Google Cloud", slug="google-cloud", vendor="Google", category="cloud_infra", description="Connect Sentra telemetry and AI workloads to Google Cloud services.", logo_key="gcp", pricing_model="enterprise", rating=4.7, review_count=980, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="high", tags=["cloud", "ai", "analytics"], version="4.6.0", monthly_price=349, trial_available=False, featured=False),
    app(app_id="APP-CLOUDFLARE", name="Cloudflare", slug="cloudflare", vendor="Cloudflare", category="cloud_infra", description="Edge security, Zero Trust access, and traffic protection for Sentra deployments.", logo_key="cloudflare", pricing_model="per_workspace", rating=4.7, review_count=870, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="medium", tags=["edge", "waf", "zero trust"], version="3.8.3", monthly_price=149, trial_available=True, featured=False),
    app(app_id="APP-OKTA", name="Okta", slug="okta", vendor="Okta", category="security", description="SSO-ready identity federation and lifecycle controls for enterprise tenants.", logo_key="okta", pricing_model="per_seat", rating=4.8, review_count=1120, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="medium", tags=["sso", "identity", "mfa"], version="4.0.1", monthly_price=249, trial_available=True, featured=True),
    app(app_id="APP-ENTRA", name="Microsoft Entra ID", slug="microsoft-entra-id", vendor="Microsoft", category="security", description="Enterprise identity, conditional access, and SSO integration.", logo_key="entra", pricing_model="per_seat", rating=4.8, review_count=1280, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="medium", tags=["sso", "conditional access"], version="4.4.1", monthly_price=249, trial_available=True, featured=True),
    app(app_id="APP-CROWDSTRIKE", name="CrowdStrike", slug="crowdstrike", vendor="CrowdStrike", category="security", description="Endpoint threat signals fused into SOC and autonomous response engines.", logo_key="crowdstrike", pricing_model="enterprise", rating=4.7, review_count=760, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="high", tags=["edr", "threat intel"], version="2.9.9", monthly_price=499, trial_available=False, featured=True),
    app(app_id="APP-PALO-ALTO", name="Palo Alto", slug="palo-alto", vendor="Palo Alto Networks", category="security", description="Firewall, Prisma, and network security events for Sentra SOC correlation.", logo_key="palo-alto", pricing_model="enterprise", rating=4.6, review_count=650, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="high", tags=["firewall", "network"], version="2.7.4", monthly_price=459, trial_available=False, featured=False),
    app(app_id="APP-SPLUNK", name="Splunk", slug="splunk", vendor="Cisco", category="security", description="Log forwarding, SIEM evidence, and compliance-grade event export.", logo_key="splunk", pricing_model="enterprise", rating=4.7, review_count=980, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="high", tags=["siem", "logs", "compliance"], version="3.6.0", monthly_price=399, trial_available=True, featured=False),
    app(app_id="APP-SENTINELONE", name="SentinelOne", slug="sentinelone", vendor="SentinelOne", category="security", description="Autonomous endpoint telemetry and cyber blast-radius signals.", logo_key="sentinelone", pricing_model="enterprise", rating=4.6, review_count=580, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="high", tags=["edr", "autonomous"], version="2.8.2", monthly_price=389, trial_available=False, featured=False),
    app(app_id="APP-SERVICENOW", name="ServiceNow", slug="servicenow", vendor="ServiceNow", category="itsm_ticketing", description="Open ITSM incidents and change workflows from Sentra events.", logo_key="servicenow", pricing_model="enterprise", rating=4.7, review_count=1030, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="high", tags=["itsm", "change", "tickets"], version="4.3.1", monthly_price=349, trial_available=True, featured=True),
    app(app_id="APP-JIRA-SM", name="Jira Service Management", slug="jira-service-management", vendor="Atlassian", category="itsm_ticketing", description="Create service tickets and response queues from Sentra command workflows.", logo_key="jira", pricing_model="per_seat", rating=4.6, review_count=850, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="medium", tags=["tickets", "service desk"], version="3.5.7", monthly_price=169, trial_available=True, featured=False),
    app(app_id="APP-ZENDESK", name="Zendesk", slug="zendesk", vendor="Zendesk", category="itsm_ticketing", description="Route support escalations and customer-facing crisis updates.", logo_key="zendesk", pricing_model="per_seat", rating=4.5, review_count=740, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="medium", tags=["support", "tickets"], version="2.9.4", monthly_price=139, trial_available=True, featured=False),
    app(app_id="APP-FRESHSERVICE", name="Freshservice", slug="freshservice", vendor="Freshworks", category="itsm_ticketing", description="ITSM and asset service desk integration for operational recovery.", logo_key="freshservice", pricing_model="per_seat", rating=4.4, review_count=520, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="medium", tags=["itsm", "assets"], version="2.6.2", monthly_price=129, trial_available=True, featured=False),
    app(app_id="APP-SALESFORCE", name="Salesforce", slug="salesforce", vendor="Salesforce", category="business_systems", description="Sync tenants, opportunities, renewals, and enterprise account motion.", logo_key="salesforce", pricing_model="enterprise", rating=4.8, review_count=1440, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="high", tags=["crm", "revenue", "accounts"], version="5.2.0", monthly_price=399, trial_available=True, featured=True),
    app(app_id="APP-HUBSPOT", name="HubSpot", slug="hubspot", vendor="HubSpot", category="business_systems", description="Marketing, sales, and customer success funnel sync for Sentra growth teams.", logo_key="hubspot", pricing_model="per_workspace", rating=4.7, review_count=970, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="medium", tags=["crm", "marketing"], version="4.0.5", monthly_price=249, trial_available=True, featured=False),
    app(app_id="APP-SAP", name="SAP", slug="sap", vendor="SAP", category="business_systems", description="ERP continuity, facility operations, and procurement workflows.", logo_key="sap", pricing_model="enterprise", rating=4.6, review_count=620, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="high", tags=["erp", "procurement"], version="3.3.8", monthly_price=599, trial_available=False, featured=True),
    app(app_id="APP-ORACLE", name="Oracle ERP", slug="oracle-erp", vendor="Oracle", category="business_systems", description="Financial, procurement, and enterprise operations integration.", logo_key="oracle", pricing_model="enterprise", rating=4.5, review_count=560, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="high", tags=["erp", "finance"], version="3.1.4", monthly_price=579, trial_available=False, featured=False),
    app(app_id="APP-ZOHO", name="Zoho CRM", slug="zoho-crm", vendor="Zoho", category="business_systems", description="CRM and account management integration for regional growth teams.", logo_key="zoho", pricing_model="per_seat", rating=4.4, review_count=490, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="medium", tags=["crm", "sales"], version="2.8.9", monthly_price=99, trial_available=True, featured=False),
    app(app_id="APP-AXIS", name="Axis Cameras", slug="axis-cameras", vendor="Axis Communications", category="field_facility_iot", description="CCTV device health, zone video metadata, and incident camera routing.", logo_key="axis", pricing_model="per_device", rating=4.7, review_count=690, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="high", tags=["cameras", "facility", "iot"], version="2.5.0", monthly_price=299, trial_available=False, featured=True),
    app(app_id="APP-HIKVISION", name="Hikvision", slug="hikvision", vendor="Hikvision", category="field_facility_iot", description="Camera fleet event sync for facilities with approved deployment policies.", logo_key="hikvision", pricing_model="per_device", rating=4.2, review_count=390, security_verified=True, enterprise_ready=False, region_support=["apac", "emea"], install_complexity="high", tags=["cameras", "facility"], version="2.1.2", monthly_price=229, trial_available=False, featured=False),
    app(app_id="APP-HONEYWELL", name="Honeywell", slug="honeywell", vendor="Honeywell", category="field_facility_iot", description="Building control, sensor, HVAC, and safety device integration.", logo_key="honeywell", pricing_model="enterprise", rating=4.8, review_count=820, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="high", tags=["building", "hvac", "sensors"], version="3.9.0", monthly_price=499, trial_available=False, featured=True),
    app(app_id="APP-BOSCH-FIRE", name="Bosch Fire Systems", slug="bosch-fire-systems", vendor="Bosch", category="field_facility_iot", description="Fire panel events, alarm zones, and smoke detection telemetry.", logo_key="bosch", pricing_model="enterprise", rating=4.7, review_count=610, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="high", tags=["fire", "safety", "sensors"], version="3.0.8", monthly_price=449, trial_available=False, featured=True),
    app(app_id="APP-SIEMENS", name="Siemens Smart Buildings", slug="siemens-smart-buildings", vendor="Siemens", category="field_facility_iot", description="Smart building telemetry, access zones, and facility automation.", logo_key="siemens", pricing_model="enterprise", rating=4.7, review_count=640, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="high", tags=["building", "automation"], version="3.7.1", monthly_price=499, trial_available=False, featured=False),
    app(app_id="APP-SCHNEIDER", name="Schneider Electric", slug="schneider-electric", vendor="Schneider Electric", category="field_facility_iot", description="Power, energy, generator, and facility resilience signals.", logo_key="schneider", pricing_model="enterprise", rating=4.6, review_count=570, security_verified=True, enterprise_ready=True, region_support=["global"], install_complexity="high", tags=["power", "energy", "resilience"], version="3.2.5", monthly_price=459, trial_available=False, featured=False),
)


APP_BY_ID = {str(item["app_id"]): dict(item) for item in MARKETPLACE_APPS}
APP_BY_SLUG = {str(item["slug"]): dict(item) for item in MARKETPLACE_APPS}
