import type { OpsFeedItem, ResponderMission, SosRequest, StaffTask, TeamMember, ZoneStatus } from "./types";

export const STAFF_ASSIGNED_ZONE = "Zone 3";

export const DEFAULT_CURRENT_ZONE = "Floor 3 - Kitchen Corridor";

export const SEEDED_SOS_REQUESTS: SosRequest[] = [
  {
    batteryLevel: "82%",
    currentZone: "Room 312",
    id: "SOS-ROOM-312",
    incidentId: "INC-KITCHEN-ZONE-B",
    kind: "injured",
    message: "Injured guest Room 312",
    networkOnline: true,
    priority: "critical",
    queuedAt: "2026-04-25T09:43:00.000Z",
    role: "guest",
    sentAt: "2026-04-25T09:43:04.000Z",
    status: "acknowledged",
  },
  {
    batteryLevel: "64%",
    currentZone: "Service Hall C",
    id: "SOS-HALL-C",
    incidentId: "INC-KITCHEN-ZONE-B",
    kind: "smoke_nearby",
    message: "Smoke nearby service hallway",
    networkOnline: true,
    priority: "high",
    queuedAt: "2026-04-25T09:44:00.000Z",
    role: "staff",
    sentAt: "2026-04-25T09:44:03.000Z",
    status: "dispatched",
  },
  {
    batteryLevel: "47%",
    currentZone: "Stairwell B landing",
    id: "SOS-STAIR-B",
    incidentId: "INC-KITCHEN-ZONE-B",
    kind: "cannot_move",
    message: "Cannot move on stairwell landing",
    networkOnline: true,
    priority: "critical",
    queuedAt: "2026-04-25T09:44:30.000Z",
    role: "guest",
    sentAt: "2026-04-25T09:44:34.000Z",
    status: "dispatched",
  },
  {
    batteryLevel: "91%",
    currentZone: "Room 318",
    id: "SOS-ROOM-318",
    incidentId: "INC-KITCHEN-ZONE-B",
    kind: "need_assistance",
    message: "Elderly guest needs assistance",
    networkOnline: true,
    priority: "high",
    queuedAt: "2026-04-25T09:45:00.000Z",
    role: "guest",
    sentAt: "2026-04-25T09:45:04.000Z",
    status: "queued",
  },
  {
    batteryLevel: "58%",
    currentZone: "North corridor",
    id: "SOS-NORTH-CORRIDOR",
    incidentId: "INC-KITCHEN-ZONE-B",
    kind: "trapped",
    message: "Door jammed near north corridor",
    networkOnline: true,
    priority: "high",
    queuedAt: "2026-04-25T09:45:30.000Z",
    role: "guest",
    sentAt: "2026-04-25T09:45:34.000Z",
    status: "queued",
  },
  {
    batteryLevel: "73%",
    currentZone: "Dining vestibule",
    id: "SOS-DINING",
    incidentId: "INC-KITCHEN-ZONE-B",
    kind: "medical_help",
    message: "Medical help requested for dizziness",
    networkOnline: true,
    priority: "normal",
    queuedAt: "2026-04-25T09:46:00.000Z",
    role: "guest",
    sentAt: "2026-04-25T09:46:05.000Z",
    status: "queued",
  },
  {
    batteryLevel: "39%",
    currentZone: "Laundry corridor",
    id: "SOS-LAUNDRY",
    incidentId: "INC-KITCHEN-ZONE-B",
    kind: "need_assistance",
    message: "Staff member requesting backup",
    networkOnline: true,
    priority: "normal",
    queuedAt: "2026-04-25T09:46:30.000Z",
    role: "staff",
    sentAt: "2026-04-25T09:46:33.000Z",
    status: "queued",
  },
];

export const SEEDED_STAFF_TASKS: StaffTask[] = [
  {
    assignedZone: STAFF_ASSIGNED_ZONE,
    civilianCount: 18,
    createdAt: "2026-04-25T09:42:00.000Z",
    id: "TASK-GUIDE-OCCUPANTS",
    priority: "critical",
    status: "pending",
    title: "Guide occupants to Stairwell B",
  },
  {
    assignedZone: STAFF_ASSIGNED_ZONE,
    civilianCount: 6,
    createdAt: "2026-04-25T09:42:30.000Z",
    id: "TASK-VERIFY-312",
    priority: "critical",
    status: "pending",
    title: "Verify room 312 injured guest",
  },
  {
    assignedZone: STAFF_ASSIGNED_ZONE,
    civilianCount: 0,
    createdAt: "2026-04-25T09:43:00.000Z",
    id: "TASK-CHECK-SMOKE-DOOR",
    priority: "high",
    status: "accepted",
    title: "Check smoke door seal",
  },
  {
    assignedZone: "South Gate",
    civilianCount: 24,
    createdAt: "2026-04-25T09:43:30.000Z",
    id: "TASK-CLEAR-EXIT",
    priority: "high",
    status: "pending",
    title: "Clear exit queue",
  },
  {
    assignedZone: STAFF_ASSIGNED_ZONE,
    civilianCount: 3,
    createdAt: "2026-04-25T09:44:00.000Z",
    id: "TASK-SUPPORT-DISABLED",
    priority: "critical",
    status: "pending",
    title: "Support disabled guest",
  },
  {
    assignedZone: "Service Hall C",
    civilianCount: 0,
    createdAt: "2026-04-25T09:45:00.000Z",
    id: "TASK-INSPECT-CORRIDOR",
    priority: "normal",
    status: "pending",
    title: "Inspect corridor bypass",
  },
];

export const SEEDED_RESPONDER_MISSIONS: ResponderMission[] = [
  {
    distanceMeters: 42,
    etaSeconds: 95,
    id: "MISSION-ROOM-312",
    ingressRoute: "Service Hall C to Room 312",
    priority: "critical",
    routeSafety: 88,
    status: "pending",
    target: "Injured guest Room 312",
    trappedMinutes: 9,
  },
  {
    distanceMeters: 58,
    etaSeconds: 125,
    id: "MISSION-STAIR-B",
    ingressRoute: "North service stairs to Stairwell B",
    priority: "critical",
    routeSafety: 82,
    status: "accepted",
    target: "Cannot move on Stairwell B landing",
    trappedMinutes: 7,
  },
  {
    distanceMeters: 76,
    etaSeconds: 150,
    id: "MISSION-HALL-C",
    ingressRoute: "East courtyard through Service Hall C",
    priority: "high",
    routeSafety: 91,
    status: "pending",
    target: "Smoke nearby service hallway",
    trappedMinutes: 5,
  },
  {
    distanceMeters: 110,
    etaSeconds: 190,
    id: "MISSION-DINING",
    ingressRoute: "South gate to dining vestibule",
    priority: "normal",
    routeSafety: 94,
    status: "pending",
    target: "Medical help for dizziness",
    trappedMinutes: 3,
  },
];

export const SEEDED_ZONE_STATUS: ZoneStatus[] = [
  { civiliansNearby: 42, exitsOpen: 1, id: "ZONE-3", name: "Zone 3", risk: "hazard" },
  { civiliansNearby: 18, exitsOpen: 2, id: "ZONE-SOUTH", name: "South Gate", risk: "clear" },
  { civiliansNearby: 9, exitsOpen: 1, id: "ZONE-HALL-C", name: "Service Hall C", risk: "watch" },
  { civiliansNearby: 0, exitsOpen: 0, id: "ZONE-KITCHEN-B", name: "Kitchen Zone B", risk: "blocked" },
];

export const SEEDED_TEAM_MEMBERS: TeamMember[] = [
  { id: "TEAM-ALPHA", name: "Alpha Lead", role: "Fire response", status: "en_route" },
  { id: "TEAM-MEDIC", name: "Medic One", role: "Medical", status: "en_route" },
  { id: "TEAM-FLOOR", name: "Floor Marshal", role: "Zone 3", status: "clearing" },
  { id: "TEAM-SECURITY", name: "Security South", role: "Exit control", status: "on_scene" },
];

export const SEEDED_OPS_FEED: OpsFeedItem[] = [
  {
    createdAt: "2026-04-25T09:47:00.000Z",
    id: "FEED-SOS-NEW",
    message: "Injured guest Room 312 promoted to top priority.",
    priority: "critical",
    title: "New SOS request",
  },
  {
    createdAt: "2026-04-25T09:47:20.000Z",
    id: "FEED-TASK-COMPLETE",
    message: "South Gate queue reduced by staff team.",
    priority: "normal",
    title: "Task completed",
  },
  {
    createdAt: "2026-04-25T09:47:40.000Z",
    id: "FEED-CORRIDOR",
    message: "Kitchen Corridor B remains blocked, route using Service Hall C.",
    priority: "high",
    title: "Blocked corridor",
  },
  {
    createdAt: "2026-04-25T09:48:00.000Z",
    id: "FEED-ETA",
    message: "Responder ETA improved to 1m 35s for Room 312.",
    priority: "high",
    title: "Responder ETA change",
  },
  {
    createdAt: "2026-04-25T09:48:30.000Z",
    id: "FEED-EVAC",
    message: "Evac progress reached 61% for Floor 3 occupants.",
    priority: "normal",
    title: "Evac progress",
  },
];

export function buildOpsFeedItem(title: string, message: string, priority: OpsFeedItem["priority"], createdAt: string): OpsFeedItem {
  return {
    createdAt,
    id: `FEED-${createdAt.replace(/\D/g, "").slice(-8)}-${title.toUpperCase().replace(/[^A-Z0-9]/g, "-")}`,
    message,
    priority,
    title,
  };
}
