from __future__ import annotations

from datetime import datetime, timedelta, timezone
from typing import Any
from uuid import uuid4

HEALTH_STATUSES: tuple[str, ...] = ("healthy", "watch", "risk", "critical")
LIFECYCLE_STAGES: tuple[str, ...] = ("onboarding", "adoption", "growth", "renewal", "rescue", "expansion")


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def future_iso(days: int) -> str:
    return (datetime.now(timezone.utc) + timedelta(days=days)).isoformat()


def account_id() -> str:
    return f"CS-{uuid4().hex[:10].upper()}"


DEMO_SUCCESS_ACCOUNTS: tuple[dict[str, Any], ...] = (
    {
        "tenant_id": "TEN-BALA-UNI",
        "workspace_name": "Bala University",
        "plan": "enterprise",
        "MRR": 14_200,
        "seats_used": 84,
        "seats_limit": 140,
        "feature_usage": {"soc": 88, "geo": 81, "ai": 76, "reports": 64, "osint": 72},
        "login_frequency": 82,
        "API_usage": 38_400,
        "report_usage": 34,
        "AI_actions_used": 212,
        "adoption_score": 84,
        "onboarding_completion": 100,
        "stakeholder_engagement": 86,
        "support_tickets": 3,
        "avg_resolution_time": 3.4,
        "NPS_score": 9,
        "CSAT_score": 96,
        "payment_status": "healthy",
        "uptime_experience": 99,
        "sentiment_trend": "rising",
        "renewal_date": future_iso(78),
        "contract_value": 170_400,
        "account_owner": "Maya Iyer",
        "lifecycle_stage": "growth",
    },
    {
        "tenant_id": "TEN-BALA-MFG",
        "workspace_name": "Bala Manufacturing",
        "plan": "business",
        "MRR": 5_400,
        "seats_used": 14,
        "seats_limit": 50,
        "feature_usage": {"soc": 61, "geo": 44, "ai": 38, "reports": 34, "osint": 22},
        "login_frequency": 42,
        "API_usage": 14_100,
        "report_usage": 8,
        "AI_actions_used": 53,
        "adoption_score": 48,
        "onboarding_completion": 72,
        "stakeholder_engagement": 39,
        "support_tickets": 9,
        "avg_resolution_time": 14.2,
        "NPS_score": 5,
        "CSAT_score": 72,
        "payment_status": "healthy",
        "uptime_experience": 96,
        "sentiment_trend": "falling",
        "renewal_date": future_iso(29),
        "contract_value": 64_800,
        "account_owner": "Jonah Reed",
        "lifecycle_stage": "rescue",
    },
    {
        "tenant_id": "TEN-BALA-HOSP",
        "workspace_name": "Bala Hospital",
        "plan": "government",
        "MRR": 22_000,
        "seats_used": 212,
        "seats_limit": 420,
        "feature_usage": {"soc": 92, "geo": 86, "ai": 82, "reports": 79, "osint": 66},
        "login_frequency": 91,
        "API_usage": 61_200,
        "report_usage": 48,
        "AI_actions_used": 344,
        "adoption_score": 88,
        "onboarding_completion": 96,
        "stakeholder_engagement": 90,
        "support_tickets": 5,
        "avg_resolution_time": 4.1,
        "NPS_score": 9,
        "CSAT_score": 94,
        "payment_status": "healthy",
        "uptime_experience": 99,
        "sentiment_trend": "rising",
        "renewal_date": future_iso(132),
        "contract_value": 264_000,
        "account_owner": "Priya Raman",
        "lifecycle_stage": "expansion",
    },
    {
        "tenant_id": "TEN-METRO-CAMPUS",
        "workspace_name": "Metro Campus Group",
        "plan": "business",
        "MRR": 8_800,
        "seats_used": 39,
        "seats_limit": 50,
        "feature_usage": {"soc": 77, "geo": 70, "ai": 68, "reports": 53, "osint": 51},
        "login_frequency": 68,
        "API_usage": 26_900,
        "report_usage": 18,
        "AI_actions_used": 131,
        "adoption_score": 73,
        "onboarding_completion": 88,
        "stakeholder_engagement": 69,
        "support_tickets": 4,
        "avg_resolution_time": 5.6,
        "NPS_score": 8,
        "CSAT_score": 88,
        "payment_status": "healthy",
        "uptime_experience": 98,
        "sentiment_trend": "stable",
        "renewal_date": future_iso(58),
        "contract_value": 105_600,
        "account_owner": "Aisha Grant",
        "lifecycle_stage": "renewal",
    },
    {
        "tenant_id": "TEN-TITAN-IND",
        "workspace_name": "Titan Industrial",
        "plan": "enterprise",
        "MRR": 18_600,
        "seats_used": 108,
        "seats_limit": 190,
        "feature_usage": {"soc": 84, "geo": 78, "ai": 75, "reports": 72, "osint": 59},
        "login_frequency": 79,
        "API_usage": 52_100,
        "report_usage": 41,
        "AI_actions_used": 287,
        "adoption_score": 82,
        "onboarding_completion": 93,
        "stakeholder_engagement": 80,
        "support_tickets": 6,
        "avg_resolution_time": 6.3,
        "NPS_score": 8,
        "CSAT_score": 90,
        "payment_status": "healthy",
        "uptime_experience": 98,
        "sentiment_trend": "rising",
        "renewal_date": future_iso(87),
        "contract_value": 223_200,
        "account_owner": "Elena Brooks",
        "lifecycle_stage": "expansion",
    },
    {
        "tenant_id": "TEN-SMARTCARE",
        "workspace_name": "SmartCare Network",
        "plan": "enterprise",
        "MRR": 16_300,
        "seats_used": 47,
        "seats_limit": 160,
        "feature_usage": {"soc": 58, "geo": 42, "ai": 44, "reports": 39, "osint": 35},
        "login_frequency": 36,
        "API_usage": 19_700,
        "report_usage": 11,
        "AI_actions_used": 73,
        "adoption_score": 52,
        "onboarding_completion": 81,
        "stakeholder_engagement": 34,
        "support_tickets": 11,
        "avg_resolution_time": 18.0,
        "NPS_score": 4,
        "CSAT_score": 68,
        "payment_status": "past_due",
        "uptime_experience": 95,
        "sentiment_trend": "falling",
        "renewal_date": future_iso(12),
        "contract_value": 195_600,
        "account_owner": "Noah Singh",
        "lifecycle_stage": "rescue",
    },
    {
        "tenant_id": "TEN-GOVSECURE",
        "workspace_name": "GovSecure South",
        "plan": "government",
        "MRR": 27_500,
        "seats_used": 328,
        "seats_limit": 600,
        "feature_usage": {"soc": 91, "geo": 89, "ai": 84, "reports": 86, "osint": 75},
        "login_frequency": 87,
        "API_usage": 88_000,
        "report_usage": 62,
        "AI_actions_used": 411,
        "adoption_score": 90,
        "onboarding_completion": 100,
        "stakeholder_engagement": 92,
        "support_tickets": 7,
        "avg_resolution_time": 3.8,
        "NPS_score": 10,
        "CSAT_score": 97,
        "payment_status": "healthy",
        "uptime_experience": 99,
        "sentiment_trend": "rising",
        "renewal_date": future_iso(44),
        "contract_value": 330_000,
        "account_owner": "Camille Ortiz",
        "lifecycle_stage": "renewal",
    },
)
