import type { IntegrationHubLogs, IntegrationHubSummary } from "@/lib/integrations/types";

export const fallbackIntegrationHubSummary: IntegrationHubSummary = {
  connectors: [
    {
      connector_id: "CON-SLACK",
      tenant_id: "TEN-GRAND-MERIDIAN",
      name: "Slack Crisis Bridge",
      category: "enterprise",
      status: "connected",
      health: 98,
      auth_mode: "OAuth",
      token_state: "healthy",
      scopes: ["chat:write", "channels:read"],
      last_sync: "2026-04-26T07:50:00+00:00",
      latency_ms: 94,
      mapped_entities: 48,
    },
    {
      connector_id: "CON-SERVICENOW",
      tenant_id: "TEN-GRAND-MERIDIAN",
      name: "ServiceNow Response Flow",
      category: "enterprise",
      status: "degraded",
      health: 86,
      auth_mode: "API key",
      token_state: "rotating",
      scopes: ["incidents.write", "tasks.read"],
      last_sync: "2026-04-26T07:25:00+00:00",
      latency_ms: 410,
      mapped_entities: 39,
    },
    {
      connector_id: "CON-FIRE-PANEL",
      tenant_id: "TEN-BALA-HOSP",
      name: "Fire Panel Gateway",
      category: "iot",
      status: "connected",
      health: 95,
      auth_mode: "mTLS",
      token_state: "healthy",
      scopes: ["alarms.read", "events.read"],
      last_sync: "2026-04-26T07:51:00+00:00",
      latency_ms: 84,
      mapped_entities: 124,
    },
    {
      connector_id: "CON-OKTA",
      tenant_id: "TEN-GOVSECURE",
      name: "Okta Workforce Identity",
      category: "security",
      status: "connected",
      health: 97,
      auth_mode: "OIDC",
      token_state: "healthy",
      scopes: ["users.read", "groups.read"],
      last_sync: "2026-04-26T07:48:00+00:00",
      latency_ms: 126,
      mapped_entities: 210,
    },
  ],
  categories: { enterprise: 2, iot: 1, security: 1 },
  connected: 3,
  degraded: 1,
  avg_health: 94,
  avg_latency_ms: 179,
  failed_integrations: [
    {
      log_id: "SYNC-002",
      tenant_id: "TEN-GRAND-MERIDIAN",
      connector_id: "CON-SERVICENOW",
      status: "retrying",
      message: "Task write delayed by remote rate limit",
      latency_ms: 812,
      created_at: "2026-04-26T07:25:00+00:00",
    },
  ],
  permission_scopes: ["alarms.read", "channels:read", "chat:write", "events.read", "groups.read", "incidents.write", "tasks.read", "users.read"],
  data_mappings: [
    { source: "ServiceNow incident", target: "Sentra incident", coverage: 96 },
    { source: "Fire panel alarm", target: "hazard event", coverage: 98 },
    { source: "Okta group", target: "RBAC role", coverage: 92 },
  ],
  automations: [
    {
      automation_id: "AUTO-INCIDENT-SLACK",
      tenant_id: "TEN-GRAND-MERIDIAN",
      name: "Incident -> Slack -> ServiceNow",
      trigger: "incident.created",
      condition: "severity >= high",
      actions: ["create war room", "open ServiceNow task", "notify exec"],
      status: "active",
      runs_today: 42,
      success_rate: 99,
    },
    {
      automation_id: "AUTO-PANIC-SMS",
      tenant_id: "TEN-BALA-HOSP",
      name: "Panic -> SMS + Teams",
      trigger: "behavior.panic_risk",
      condition: "confidence >= 85",
      actions: ["send SMS", "post Teams card", "escalate silence"],
      status: "active",
      runs_today: 18,
      success_rate: 97,
    },
  ],
  reliability: { circuit_breakers: 4, fallback_caches: 7, retry_queues: 3, idempotency_keys_today: 18420 },
};

export const fallbackIntegrationHubLogs: IntegrationHubLogs = {
  logs: fallbackIntegrationHubSummary.failed_integrations,
  failed: [],
  retrying: fallbackIntegrationHubSummary.failed_integrations,
  events: [
    { event_id: "INT-EVT-00001", action: "connector_connected", created_at: "2026-04-26T07:48:00+00:00" },
    { event_id: "INT-EVT-00002", action: "connector_tested", created_at: "2026-04-26T07:50:00+00:00" },
  ],
};
